//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CefInsiders.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CefInsider
    {
        public int Id { get; set; }
        public string RecordDate { get; set; }
        public int DataType { get; set; }
        public double Average { get; set; }
        public string DisplayDate { get; set; }
    }
}
